Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,17 @@ jobs:
           key: ${{ runner.os }}-sonar
           restore-keys: ${{ runner.os }}-sonar
 
+      - name: Check SONAR_TOKEN exists
+        working-directory: appointment-scheduling
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: |
+          if [ -z "$SONAR_TOKEN" ]; then
+            echo "SONAR_TOKEN is missing"
+            exit 1
+          fi
+          echo "SONAR_TOKEN exists"
+
       - name: Build, test, and SonarCloud analysis
         working-directory: appointment-scheduling
         env:
@@ -40,4 +51,5 @@ jobs:
           mvn -B clean verify sonar:sonar \
             -Dsonar.projectKey=appointment-2026_SoftwareProject \
             -Dsonar.organization=appointment-2026 \
-            -Dsonar.host.url=https://sonarcloud.io
+            -Dsonar.host.url=https://sonarcloud.io \
+            -Dsonar.token=$SONAR_TOKEN
